### ISSUE TITLE
Bitcode enabled by default

### ISSUE THREAD

**Issue by yurkinh** [roubachof/Maui.Nuke#1]
Hello,
When I tried to publish an app with Maui.Nuke and got an error from Apple.
_ITMS-90482: Invalid Executable - The executable 'MyApp.app/Frameworks/Nuke.framework/Nuke' contains bitcode._
There is [workaround](https://github.com/dotnet/maui/issues/10989#issuecomment-1304317816) for urgent cases but all libs built with XCode 14 should go with disabled Bitcode

**Comment by roubachof** [comment]
You want to post your issue here: https://github.com/roubachof/NukeProxy

**Comment by yurkinh** [comment]
Ok. Thanks.
